### ISSUE TITLE
"This analysis takes a normalized expression matrix as input", FPKM matrix could be?

### ISSUE THREAD

**Issue by jiehuichen** [saralinker/brainImageR#2]
Hi Sara,

To predict the developmental time point, we should take a normalized expression matrix as input according to the manual. 

Can I use FPKM matrix of the test samples as input? 

Usually, what kind of matrix can be used, FPKM, CPM,TPM ?

Thanks for your help
Jiehui

**Comment by saralinker** [comment]
Hi Jiehui, 

The algorithm was intended to work with any normalized matrix. This refers to both the standardization for library size and the final distribution of the data. For example, log TPM (or FPKM, CPM, etc...) values would work. This is because the data is scaled before it's analyzed. With that being said I've only tried with FPKM and TPM, I have not yet used CPM. Happy to work through this with you if you have any issues. 

Best,
Sara

**Comment by jiehuichen** [comment]
Got it, many thanks.

Best,
Jiehui
